### ISSUE TITLE
Tutorials: toDo list of missing items

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#68]
Tutorials: toDo list of missing items

### vision
- [ ] Document pure RGB cameras (interfaces and examples)
  - http://www.yarp.it/classyarp_1_1dev_1_1IFrameGrabberImage.html
  - http://www.yarp.it/classyarp_1_1dev_1_1IFrameGrabberControls.html
- [ ] Document new IDetector (interface and examples)

### sound
- [ ] ASR (sphinx)
- [ ] TTS (eSpeak/mbrola)

### path-planning
- [ ] Document path-planning interface as in [BiRRT trajectory planning in joint space with TEO
](https://www.youtube.com/watch?v=Cxs6ZPnZ3JE)
